volumes:
  overpass-db:

version: '3.8'
services:
  overpass:
    # specify the image here
    image: lhbelfanti/overpass-api:1.0.0
    container_name: overpass
    build: .
    ports:
      - 12345:80
    volumes:
      # use a docker managed volume
      - overpass-db:/db
    environment:
      - OVERPASS_PLANET_URL=http://download.geofabrik.de/south-america/argentina-latest.osm.pbf
      - OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/south-america/argentina/minute/
      - OVERPASS_UPDATES_ENABLED=false
      - OVERPASS_UPDATE_SLEEP=3600
      - OVERPASS_FCGI_MAX_REQUESTS=10000
      - OVERPASS_FCGI_MAX_ELAPSED_TIME=900
      - OVERPASS_REGEXP_ENGINE=PCREJIT
    healthcheck:
      test:
        - CMD-SHELL
        - curl -qf 'http://localhost/api/interpreter?data=\[out:json\];node(1);out;'
          | jq '.generator' | grep -q Overpass | echo '' || exit 1
      timeout: 15s
      interval: 10s
      retries: 3
      start_period: 2h0m0s